baseURL = "http://honestwork.org/"
languageCode = "en-us"
title = "Honest Work"
theme = "honestwork"

[markup.goldmark.renderer]
unsafe= true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about hugo"
    url = "/about/"
    weight = -110